### ISSUE TITLE
wrote new parser, but I get "java.lang.NoSuchMethodError: No such DSL method"

### ISSUE THREAD

**Issue by ferkulat** [uhafner/warnings-ng-plugin-devenv#17]
Hello, 
I added a new parser. But when testing it with jenkins
~~~~
recordIssues tool:codeChecker(pattern: 'b/static_analysis_report.txt', name: 'Codechecker')
~~~~
I get:
~~~~
java.lang.NoSuchMethodError: No such DSL method 'codeChecker' found among steps [archive, bat, build, catchError, checkout, 
~~~~
in the attached screenshot you can see it is listed in symbols.
I feel I am so close. But maybe I made a beginner mistake.

I did setup the jenkins pipeline in another jenkins instance, where I manually uploaded   'warnings-ng.hpi' and 'analysis-model-api.hpi' to. I did not use the docker instance from this devenv.
My repositories are:
https://github.com/ferkulat/analysis-model/tree/add_parser_for_codechecker
https://github.com/ferkulat/warnings-ng-plugin/tree/add_parser_for_codechecker

I did not want to make a pull request, because its not done yet.
But I could do that anyway, if that is better for discussion.

![Screenshot from 2021-10-31 21-15-00](https://user-images.githubusercontent.com/1757239/139599837-33a4819b-b6ce-4bf7-bf1f-3d3e7393021e.png)
.

**Comment by uhafner** [comment]
Sorry, seems that I missed this issue here. Your approach seems correct. Is it possible that someone else already is using the codeChecker symbol? You create a draft PR where we can discuss that topic. BTW: it is not required anymore to create a model element in the warnings ng plugin. It is sufficient to update the parser. Did you create the analysis-model-api-plugin using the changed version?

**Comment by ferkulat** [comment]
got it working. I am not really sure, why it did not work before. maybe I got the ID wrong. and it did not match in `warnings-ng-plugin` and `analysis-model`.
https://github.com/jenkinsci/analysis-model/pull/706
https://github.com/jenkinsci/warnings-ng-plugin/pull/1110
